# -*- coding: utf-8 -*-
"""RAG.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kc-CdTTJi4YzdIAiYaa1Jeei_Cjl7nl0
"""

!pip install langchain-community --quiet

!pip install pypdf --quiet

from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("/content/COMPLETE SPECIFICATION (1).pdf")
pdf = loader.load()

pdf[0]

len(pdf)

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
            chunk_size=1024,
            chunk_overlap=200
        )

chunked_pdf = splitter.split_documents(pdf)

len(chunked_pdf)

from langchain_community.embeddings import HuggingFaceEmbeddings

multilingual_embeddings = HuggingFaceEmbeddings(model_name='intfloat/multilingual-e5-large')

multilingual_embeddings.embed_query(chunked_pdf[0].page_content)

len(multilingual_embeddings.embed_query(chunked_pdf[0].page_content) )

!pip install chromadb --quiet

from langchain_community.vectorstores import Chroma

vectordb = Chroma.from_documents(
            documents=chunked_pdf,
            embedding=multilingual_embeddings,
            persist_directory="/db/chroma/"
        )

question = "summarize all the 10 claims"

vectordb.similarity_search(question, k=3)

vectordb.similarity_search_with_score(question, k=3)

vectordb.max_marginal_relevance_search(question, k=3, fetch_k=10)

!pip install langchain-groq --quiet

import getpass
import os

if "GROQ_API_KEY" not in os.environ:
    os.environ["GROQ_API_KEY"] = getpass.getpass("Enter your Groq API key: ")

from langchain_groq import ChatGroq

llm = ChatGroq(
            model="llama-3.1-8b-instant",
            temperature=0,
            max_tokens=250,
        )

response = llm.invoke("summarize all claims")
response.content

from langchain_core.messages import SystemMessage, HumanMessage, AIMessage

system_prompt = (
        "You are an assistant for question-answering tasks. Use the following pieces of retrieved context to answer the question",
        "If you don't know the answer, just say that you don't know. Use three sentences maximum and keep the answer concise",
        "Answer all questions to the best of your ability",
        )

retrieved_docs = vectordb.similarity_search(question, k=5)

context = " ".join([doc.page_content for doc in retrieved_docs])

system_prompt_as_string = " ".join(system_prompt)

messages = [
    SystemMessage(content=system_prompt_as_string),
    HumanMessage(
        content=f"""
Use the following context to answer the question.
If the answer is not in the context, say you don't know.

Context:
{context}

Question:
{question}
"""
    )
]

result = llm.invoke(messages)
result.content